### ISSUE TITLE
Inefficient transaction signing

### ISSUE THREAD

**Issue by ray66rus** [marvin-we/steem-java-api-wrapper#123]
In [SignedTransaction class](https://github.com/marvin-we/steem-java-api-wrapper/blob/master/core/src/main/java/eu/bittrade/libs/steemj/base/models/SignedTransaction.java#L192) there is a following code:
```
ECDSASignature signature = requiredPrivateKey.sign(messageAsHash);

 /* find a correct public key type */
 /* create signed transaction */

if (isCanonical(signedTransaction))
    /* change timestamp and start all over */
else
    /* Signature is canonical, all done */
```

The problem is that finding a key is pretty time-consuming operation, while the result of it doesn't affect the result of signed transaction canonical check. So I think it would be better to change the code the following way:
```
ECDSASignature signature = requiredPrivateKey.sign(messageAsHash);
/* create signed transaction */
if (isCanonical(signedTransaction))
    /* change timestamp and start all over */
else
    /* Signature is canonical, continue */

 /* find a correct public key type AND update signed transaction */

```

**Comment by marvin-we** [comment]
Hay @ray66rus ,

Commit b1213f0506c6eaa216815eb609f24728b792372c implements the change suggested by you :) I did some tests and due to your change the sign method was about 15% faster - Thank you for that hint!

I am still not sure if calculating the key type is needed at all because in the current implementation the original key type is stored in the privateKeyStorage .. I guess working on #63 will bring the final answer 👍 

Thank you once again and best regards!
