### ISSUE TITLE
Custom JSON Operation unable to broadcast transaction

### ISSUE THREAD

**Issue by Atherz97** [marvin-we/steem-java-api-wrapper#130]
Trying to reblog a post:

```
ReblogOperation o = new ReblogOperation();
o.setAccount(myAccount);
o.setAuthor(d.getAuthor());
o.setPermlink(d.getPermlink());
// d = discussion object containing the post author and permlink to reblog

CustomJsonOperation c = new CustomJsonOperation(a, a, String.valueOf(d.getId()), CommunicationHandler.getObjectMapper().writeValueAsString(o));
// a = A List<AccountName> with myAccount as its only element
// the json is correct, otherwise it'd throw a Json exception
operations.add(c);
SignedTransaction t = new SignedTransaction(globalProperties.getHeadBlockId(), operations, null);

t.validate();
t.sign();
api.broadcastTransaction(t);
```

The problem is that the CustomJsonOperation requires two parameters, requiredAuths and requiredPostingAuths, however when using both with my account (which has both the POSTING and ACTIVE keys), I get this error:

```
Steem does not allow to process Operation requiring a POSTING key together with Operations requireing an ACTIVE or OWNER key.
```
And when providing null into any one of the two, the broadcasting seems to not throw any exceptions; however the posts are not reblogged. I'm not sure what the issue is, since this follows the basic flow of a normal Voting transaction too (operation -> add to list -> create transaction -> sign -> broadcast). Any pointers, or is this a lower-level issue?

**Comment by marvin-we** [comment]
Hay @Atherz97 and thank you for creating the issue here!

Using the CustomJsonOperations is a huge fight and requires some trial and error in general - I see a lot of simular questions and problems in all other Steem-API projects like Steem-js or piston - So using them requires a lot of documentation.

I've added the "enhancement" label to this issue as I plan to implement something I call "simplyfied operation" for the reblog operation too, so that it will be much easier in the future.

Back to your problem and my guess what is going wrong here:

So a CustomJsonOperation is quite "stupid", as it does not know about its payload and which keys are required for it. Because of this it allows you to define both: Accounts whose private posting is required AND accounts whose private active key is required. As the error method says, on top of this it is not allowed to provide both of them :D Complex, isn't it? 

So the first answer is:

A reblog operation requires the private posting key of the account that wants to reblog the Operation --> Create a list that only contains your account and set this last as the `requiredPostingAuths : List<AccountName>`. The `requiredAuths` needs to be `null`.

As you said, this will at least pass all Steem validations and the transaction is accepted - But the post is not reblogged. The answer for this also requires some deep knowledge:

A CustomJsonOperation has an ID field. When a Steem Node receives a CustomJsonOperation it is searching for a class that can do something with the json payload based on this id - When no class is found, the CustomJsonOperation is just dropped and not processed which for sure happened in your case.

The solution should be to provide the correct id of the class that can process the json of the reblog operation. For operations related to the follow_api, the `id` should be `follow` which you can simply provide as a String.

Please test this and let me know what I can improve (e.g. in the JavaDoc,...) to make this more clear.

If you want to give something back I would love to see a documentation about this in the wiki which you could share as a post on Steemit - If you go for this let me know about it and I'll resteem it.

Best regards!

**Comment by marvin-we** [comment]
Hay @Atherz97 ,

as promised I've added a simplfied reblog operation:

```JAVA
// Let the default account ("steemj") resteem a post".
steemJ.reblog(new AccountName("dez1337"), new Permlink("steemj-v0-4-0-has-been-released-integrate-steem-into-your-java-project"));
```

Which will be availble in the next version.

Anyway I am more than interested if the solution suggested in the first post ist working - So please provide some feedback :) In case of additional problems I'll reopen the ticket.

**Comment by Atherz97** [comment]
Great! And changing the ID field definitely worked! However, after that using the ReblogOperation and translating it into JSON triggered a Steem error of an unknown field "reblog_operation". Changing it to "reblog" like the original [link](https://github.com/steemit/steem-js/issues/163) you sent me (thus just using a normal CustomJsonOperation) fixed it fully.

So I think the only real issue is changing the ReblogOperation's Json representation's first field to "reblog_operation" to "reblog", and then all else would work. However, if it also works through a call in the API now, that's even better :) Thank you for the help, sir!

**Comment by marvin-we** [comment]
Hay @Atherz97  - Thank you for the feedback :) Great that its now working for you.

> So I think the only real issue is changing the ReblogOperation's Json representation's first field to "reblog_operation" to "reblog", and then all else would work.

That's what I did when I've implemented the "simplified operation" - In addition, the follow_operation and the reblog_operation now both have a .toJson() method that will generate the correct json.

**Comment by natttttan** [comment]
> steemJ.reblog(new AccountName("dez1337"), new Permlink("steemj-v0-4-0-has-been-released-integrate-steem-into-your-java-project"));

> Which will be availble in the next version.

Is it available already, or it is just me not knowing how to use it? Thanks!

**Comment by marvin-we** [comment]
It is availble since SteemJ 0.4.1 :)

Please checkout the Wiki article: https://github.com/marvin-we/steem-java-api-wrapper/wiki/Operations 

And let me know if its now working for you :)

Thank you and best regards!
