### ISSUE TITLE
The connection has been closed. Switching the endpoint and reconnecting.

### ISSUE THREAD

**Issue by michael-newsrx** [marvin-we/steem-java-api-wrapper#202]
Is there any recommendations to mitigate the following new issue when communicating with the blockchain? Have they done some sort of new connection limiting or is this just some transient thing that needs ignoring? Does steemJ come with multiple endpoints predefined or only one? Using v4.
```
WARNING: The connection has been closed. Switching the endpoint and reconnecting.
Jan 09, 2018 4:17:34 PM eu.bittrade.libs.steemj.communication.CommunicationHandler performRequest
WARNING: The connection has been closed. Switching the endpoint and reconnecting.
```

**Comment by Tyvain** [comment]
Same pb here...

**Comment by michael-newsrx** [comment]
Seems to be happening during bandwidth issues, probably nodes are being DOS'ed or something.

**Comment by marvin-we** [comment]
Hay @Tyvain , hay @michael-newsrx - Thank you guys for reporting this issue.

Yeah, it seems to work again. 

> Have they done some sort of new connection limiting or is this just some transient thing that needs ignoring?

No - There will be some downtime for HF 0.20 in some weeks(?), but beside that I am not aware of downtimes or limitations. 

Just a quick hint: I think SteemJ 0.4.x will no longer work as HF 0.20 comes with the restructured API. So I will try my best to provide the 0.5.0 version before they switch the node so that you can update as soon as the switch happend. In general it would be the best to have your own node for your services so that you can decide when you change the HF version, but due to the high hardware requirements this will be a dream for most of our small projects :(

> Does steemJ come with multiple endpoints predefined or only one? 

It is currently shipped with one node, but it would support multiple ones in general (There is a SteemJConfig.addEndpointURI method to add additional ones).

If you no a node that has most of the plugins added and is maintained well I am more then fine with adding it by default. Do you have one in mind? =)
