### ISSUE TITLE
 Can I post a blog using this library?

### ISSUE THREAD

**Issue by sesangsokuro** [marvin-we/steem-java-api-wrapper#36]
I could not find a BlogOperation. or like this.

If so, can I upload the image together?

**Comment by marvin-we** [comment]
Hay @sesangsokuro ,

To be honest: I've never tested that, but if you take a look at a new post at Steemd.com (like [this one](https://steemd.com/tx/407773bbdf75a909fdba69089d29c1955d6c9ab4) you can see that it seems to be done by a normal comment operation. 

I think the only difference is that you need to set the "parentAuthor" to newAccountName(""). 

Please let me know if its working.

Best regards!

**Comment by sesangsokuro** [comment]
when i test it ( using comment operation with parenthauthor and parent permlink set to ""  ).

it occurs Assert Exception.

permlink.size() > STEEMIT_MIN_PERMLINK_LENGTH && permlink.size() < STEEMIT_MAX_PERMLINK_LENGTH

// STEEMIT_MIN_PERMLINK_LENGTH  = 0
// STEEMIT_MAX_PERMLINK_LENGTH = 256

so i send to parent 2 parameter ( parentPermlink, and parentAuthor ) " " // single space character

it occured error! ( account validation name )

how can i set parent account name? ( steemit? )

when i set it "steemit" they send to me error "Unrecognized field "author" "

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "n" (class eu.bittrade.libs.steemj.base.models.error.SteemData), not marked as ignorable (8 known properties: "call.method", "posting", "what", "call.params", "type", "name", "id", "api"])
 at [Source: {"id":10,"error":{"code":1,"message":"10 assert_exception: Assert Exception\nis_valid_account_name( name ): Account name   is invalid\n    {\"n\":\" \"}\n    th_a  steem_operations.hpp:13 validate_account_name\n\n    {\"call.method\":\"call\",\"call.params\":[\"network_broadcast_api\",\"broadcast_transaction\",[{\"operations\":[[\"comment\",{\"parent_author\":\" \",\"parent_permlink\":\" \",\"author\":\"sesangsokuro\",\"permlink\":\"-20170809t052633577z\",\"title\":\"titletile\",\"body\":\"titletile\",\"json_metadata\":\"{\\\"tags\\\":[\\\"kr\\\"],\\\"app\\\":\\\"steemup/0.1\\\"}\"}]],\"extensions\":[],\"ref_block_num\":62914,\"ref_block_prefix\":3120331242,\"expiration\":\"2017-08-09T06:25:36\",\"signatures\":[\"1c2882b20b1bf7c73c6a427d0cf0ae4808880fa677fcd61504310ab7c3b1c5497860130e26837fcab1e4045a84d1014f0a945ef6a01ade58fea5e34f5bd2ea568e\"]}]]}\n    th_a  websocket_api.cpp:124 on_message","data":{"code":10,"name":"assert_exception","message":"Assert Exception","stack":[{"context":{"level":"error","file":"steem_operations.hpp","line":13,"method":"validate_account_name","hostname":"","thread_name":"th_a","timestamp":"2017-08-09T05:27:08"},"format":"is_valid_account_name( name ): Account name ${n} is invalid","data":{"n":" "}},{"context":{"level":"warn","file":"websocket_api.cpp","line":124,"method":"on_message","hostname":"","thread_name":"th_a","timestamp":"2017-08-09T05:27:08"},"format":"","data":{"call.method":"call","call.params":["network_broadcast_api","broadcast_transaction",[{"operations":[["comment",{"parent_author":" ","parent_permlink":" ","author":"sesangsokuro","permlink":"-20170809t052633577z","title":"titletile","body":"titletile","json_metadata":"{\"tags\":[\"kr\"],\"app\":\"steemup/0.1\"}"}]],"extensions":[],"ref_block_num":62914,"ref_block_prefix":3120331242,"expiration":"2017-08-09T06:25:36","signatures":["1c2882b20b1bf7c73c6a427d0cf0ae4808880fa677fcd61504310ab7c3b1c5497860130e26837fcab1e4045a84d1014f0a945ef6a01ade58fea5e34f5bd2ea568e"]}]]}}]}}}; line: 1, column: 1244] (through reference chain: eu.bittrade.libs.steemj.base.models.error.SteemError["error"]->eu.bittrade.libs.steemj.base.models.error.SteemErrorDetails["data"]->eu.bittrade.libs.steemj.base.models.error.SteemErrorData["stack"]->java.lang.Object[][0]->eu.bittrade.libs.steemj.base.models.error.SteemStack["data"]->eu.bittrade.libs.steemj.base.models.error.SteemData["n"])


What more can I do?

---

ps.
Separately .. Congratulations on the release of version 0.3.2.
But ... I felt it during my last update. Can you write an @deprecated annotation?
All of the existing features are messed up and the new features are so structurally different.

**Comment by marvin-we** [comment]
Hay @sesangsokuro ,

I am always happy to see you here :) 👍 - Sadly, steemd is currently not showing transactions, so I extracted one myself:

```JSON
[
    [
        "comment",
        {
            "parent_author": "",
            "parent_permlink": "poetry",
            "author": "simaroy",
            "permlink": "5za2nk-an-original-bengali-poem",
            "title": "An original bengali poem:  \u09b8\u09c7\u0987 \u09b0\u09be\u09a4\u09c7\u09b0 \u09ac\u09c3\u09b7\u09cd\u099f\u09bf",
            "body": "@@ -787,17 +787,17 @@\n %E0%A6%B0 %E0%A6%AE%E0%A6%A7%E0%A7%8D%E0%A6%AF%E0%A7%87 \n-%E0%A6%AF\n+%E0%A6%98\n %E0%A6%9F%E0%A6%B2  %E0%A6%95%E0%A6%BF%E0%A6%AD%E0%A6%BE\n",
            "json_metadata": "{\"tags\":[\"poetry\",\"literature\",\"blog\",\"writing\"],\"image\":[\"https:\/\/steemitimages.com\/DQmQHX3R8ETnzKFnHMTQ9ZLbR9ZnC8dYRMEMJrFX63VCNJR\/1fbb72486206e0e47d123ad5d0160feb--rainy-mood-rainy-night.jpg\"],\"app\":\"steemit\/0.1\",\"format\":\"markdown\"}"
        }
    ]
]
```

As you can see - The permlink is still filled, but the parent_author is empty. So as I stated in my last post

> I think the only difference is that you need to set the "parent_author" to new AccountName("").

Please try to only set the parent_author to a new AccountName and let me know if it is working :)

<hr>

Thank you very much @sesangsokuro . I know that it messed up a lot and I also know that it is not professional :( Sadly, I made a lot of design mistakes when I've started this project because I wasn't aware of a lot of stuff myself. If you take this release as an example: Without those changes the custom_json_operation (used to follow, unfollow and resteem) would still not work. 

I feel pretty comfortable right now and think that most of the design mistakes are solved so I would not expect a lot more of those "heavy" changes in the future - And also - I'll keep your words in mind and try to take more care of it.

Thank you once again for all your feedback! It really helps me to improve. 

<hr>

PS: If you have a cool project and wrote about on Steemit please let me know - I would like to be the first one to vote and resteem it ;)

**Comment by sesangsokuro** [comment]
@marvin-we , Oh! Your answer works nicely. You can finally do something. thank you!

But again the question arises.
I have not seen an image file upload operation in operations.
Is there a way to upload files using steemimage.com?
---
p.s.
My project is still just a bot. I do not know if I will create a site that users will use in the future.

This feature, which I asked yesterday, will be used for the booking posting function.

If you have a lot of people who want to use these things, it would be nice to create a site.

But I'm a bit reluctant to ask the user for a posting key.

Do you know if steemconnect is safe or not?

My acquaintance says that it is reliable, but I still doubt it.

Is steemconnect a project on the steem developer team? If so, believe it or not, considering the time of Mount Songs, it's hard to trust anyone with a password.

In fact, it is still questionable whether steemj's key management will be fair. I do not know if my account will have enough funds to spend on it, because I have a small balance.

Is there any way I can be sure about this?
---
p.s.2

It looks like a job site called steemj. Is this your project?

**Comment by ismelykh** [comment]
Posting doesn't work for me too, I have the same problem as @sesangsokuro reported, "Missing posting authority". However I can comment a post.

Accodring to the steemd log I can see that condenser's 'Submit a story' is just a comment operation with an empty parent_author plus same parent_permlink and permlink fields but setting parent_author to empty string causes 'missing required posting authority'.

**Comment by marvin-we** [comment]
Hay @sesangsokuro ,

Great that is now working for you! :) 

<hr>

No, as far as I know there is currently now way to store an image on the blockchain. Websites like [steemimage.com](steemimage.com) are additional services that host the images on their own servers. To solve your problem you may search for image hoster that provide a Java API. You may want to have a look [at this discussion](https://stackoverflow.com/questions/2642570/whats-a-good-image-hosting-site-with-an-api-to-allow-me-upload-images-from-my-w).

<hr>

> But I'm a bit reluctant to ask the user for a posting key

I agree - This always feels strange, but its the easiest way for you and the users. 

What you can do as an alternative: Every user can add mutliple keys to his account - Based on that you could provide a public key that a user can add this account. This would allow you to do everything as long as the user has added your public key as an additional posting key to his account and he does not need to provide you his private key.

Regarding steemconnect - I've never used it but it is developed by a lot of well known guys like furion and I see no reason why they should be interested in scamming.

<hr> 

No it is not connected. I renamed this project to SteemJ some times ago because "steem-api-wrapper" sounds stupid :D 

To do not mess up this thread: Feel free to ping me on Steem Chat or leave me a comment on Steemit to discuss about it.

**Comment by marvin-we** [comment]
Hello @ismelykh ,

Thank you very much for your input. I guess you are using SteemJ v0.3.2 right? I've introduced a new bug with that version that uses the "parentAuthor" instead of the "author" field to sign the transaction :/ 

I've fixed this and added a new integration test to make sure that this never happens again.

<hr>

> Tbf, error handling is really bad rn, any error message from server causes bunch of output with hard understandable log, I think handling the server's errors would bring a better debug experience for users. I hope you will add it to the next release.

Yes, I am aware of that ( see #34). I've tried to parse the Steemd exceptions in the past, but they are really dynamic which makes it hard to analyse them properly. If you have some ideas how to improve this you are more than welcome - Just leave a comment in #34 .
