### ISSUE TITLE
Trouble using API in project

### ISSUE THREAD

**Issue by FullKickProductions** [marvin-we/steem-java-api-wrapper#49]
Hi, please forgive me if this question is too elementary but I'm struggling to build my project when using the latest version of the API.
It's my first time building with a local dependency in maven, so I'm sure I've done something wrong here.

I added the API to my project as a maven project (using the pom.xml) All the dependencies seem to be linking up OK but when I build I'm getting the error

> ERROR StatusLogger No log4j2 configuration file found. Using default configuration: logging only errors to the console. Set system property 'org.apache.logging.log4j.simplelog.StatusLogger.level' to TRACE to show Log4j2 internal initialization logging.

Stack overflow hasn't been much help as most of the recommendations involve creating a log4j2 file manually, which doesn't seem right.

Any insight into this problem would be greatly appreciated.

UPDATE: I get the same error when adding the jar file directly

**Comment by marvin-we** [comment]
Hay @FullKickProductions,

thank you for your question. Actually the error just says that the logging framework (log4j2) was not able to  find a log4j2.xml on the classpath. 

This xml configuration file is not included on purpose, because it would be hidden in the JAR and noone would be able to adjust the logging config. 

To solve this problem it should be enough to create this xml file and place it in your /src/main/resources folder. Here is one example file:

```XML
<?xml version="1.0" encoding="UTF-8"?>
<Configuration status="debug">
  <Appenders>
    <Console name="Console" target="SYSTEM_OUT">
      <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"/>
    </Console>
  </Appenders>
  <Loggers>
    <Root level="debug">
      <AppenderRef ref="Console"/>
    </Root>
  </Loggers>
</Configuration>
```

Please let me know if it helped :)

**Comment by FullKickProductions** [comment]
Thanks for the help, sorry to be asking such basic questions.

**Comment by marvin-we** [comment]
No problem at all - Just let me know if it is working now :)

**Comment by FullKickProductions** [comment]
Yes its working fine now.
