### ISSUE TITLE
Update the posted comment

### ISSUE THREAD

**Issue by ismelykh** [marvin-we/steem-java-api-wrapper#78]
Hey @marvin-we,

I've tried to update the body text of the posted comment and found that it's not possible, steemd returns an error, regarding to the blocks id or something like that, will try to share the exact error soon.

According to the steemd log and condenser's 'edit' thing it's the same operation but with difference in a body json field. I've tried to make exact same request, it was same according to the steemd log, but it didn't work with steemJ.

Thanks.

**Comment by marvin-we** [comment]
Hay @ismelykh ,

so I've implemented a "updatePost" method that simplifies the usage of Operations and in my tests its working fine. The new version currently has a problem with the test net as I forgot about it when implementing the validation, but this will be fixed with the first bug fix release and is tracked in #117 .

So if you need to stick with your own branch or an older version here is what you need to do to update a post:
- ParentAuthor = ""
- ParentPermlink = 1st tag (This needs to be the same one as the original one)
- Author = same author than the original post
- Permlink = same permlink than the original post

Beside that you can change all parameters as far as I have tested it.

For a comment it is nearly the same:
- ParentAuthor = original parentAuthor
- ParentPermlink = original parentPermlink
- Author = original author
- Permlink = original permlink

I hope that helps you :)
